apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-config
  namespace: airbnb
data:
  # MySQL Database Configuration
  DB_HOST: "mysql-service"
  DB_NAME: "airbnb_db"
  DB_USER: "airbnb_user"

  # MongoDB Configuration
  MONGO_HOST: "mongodb-service"
  MONGO_DB: "airbnb_sessions"
  MONGO_USER: "admin"

  # Kafka Configuration
  KAFKA_BROKER: "kafka-service:9093"

  # Application Configuration
  NODE_ENV: "production"
  PORT: "4000"
